export const API = {
  themes: [
    {
      id: 0,
      image: 'https://s29.postimg.org/i21ox7xhz/couv7wonders.jpg',
      name: 'Les 7 merveilles du monde',
      period: 'antiquity',
      description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
      nbStories: 7,
      locked: false,
      histories: [
        {
          id: 0,
          locked: false,
          image: 'https://s27.postimg.org/bskr443v7/slide1_1_1024x475.jpg',
          name: 'La pyramide de Khéops',
          period: 'antiquity',
          description: 'Elle fait partie des constructions les plus massives du monde et est la seule merveille à toujours être debout !',
          duration: 7,
          nbPages: 6,
          availability: '24/12',
          pages: [
            {
              id: 1,
              title: "L'Égypte antique",
              text: `Nous sommes en l’an 3150 avant Jésus Christ. Une nouvelle civilisation vient de naître dans le monde : La civilisation égyptienne. Les égyptiens sont un peuple d’Afrique du Nord qui vivent autour du Nil, l’un des plus grand fleuves du monde. Le Nil est l’un des rares fleuves à couler du Sud vers le Nord. \n\nLes égyptiens sont connus dans le monde entier pour être les inventeurs des hiéroglyphes, l’écriture de la langue égyptien. Ce sont des symboles qui permettent de faciliter le marché et la récolte des impôts par l’Etat. Il existe plus de 500 symboles qui représentent un mot, un son ou une situation.`,
              image: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
              content: [
                {
                  id: 0,
                  type: 'GIF',
                  paragraph: 1,
                  content: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                  data: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                },
                {
                  id: 1,
                  type: 'word',
                  paragraph: 1,
                  content: 'Hiéroglyphe',
                  data: 'Hiéroglyphe',
                },
                {
                  id: 2,
                  type: 'word',
                  paragraph: 2,
                  content: 'Pharaon',
                  data: 'Pharaon',
                },
                {
                  id: 3,
                  type: 'GIF',
                  paragraph: 2,
                  content: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                  data: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                },
              ],
            },
            {
              id: 2,
              title: 'La mythlogie égyptienne',
              text: "Il faut aussi savoir que la religion est extrêmement importante chez les égyptiens. C’est une religion polythéiste, elle possède donc de nombreux dieux. Les plus importants sont Ra, Anubis, Horus, Isis ou encore Seth. Les égyptiens croient en l’immortalité de l’âme et vont donc créer de nombreux temples à la gloire des différents dieux ainsi que des pyramides, symboles de l’élévation de l’âme.",
              image: 'https://giant.gfycat.com/WateryArtisticHamadryad.gif',
              content: [
                {
                  id: 0,
                  type: 'GIF',
                  paragraph: 1,
                  content: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                  data: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                },
                {
                  id: 1,
                  type: 'word',
                  paragraph: 1,
                  content: 'Horus',
                  data: 'Horus',
                },
              ],
            },
            {
              id: 3,
              title: 'Les pharaons',
              text: `La personne qui dirige l’ensemble des égyptiens est un Pharaon. On dit qu’il tire son pouvoir directement des dieux et qu’il est l’un de leurs descendant. Le pharaon est le symbole du pouvoir et de l’unité de la population. Parmis les plus connus nous avons : Imhotep, Toutânkhamon ou encore Ramsès II. Au total, les pharaons ont fait construire 90 pyramides en Egypte. \n\n C’est en l’an 2550 avant Jésus Christ, en Egypte, que le nouveau pharaon Khéops entre au pouvoir succédant à son père Snéfrou. C’est dès son entrée au pouvoir qu’il décide de lancer la construction de sa Pyramide. La Pyramide de Khéops reste encore aujourd’hui l’une des construction les plus imposante du monde.`,
              image: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
              content: [
                {
                  id: 0,
                  type: 'GIF',
                  paragraph: 1,
                  content: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                  data: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                },
                {
                  id: 1,
                  type: 'word',
                  paragraph: 1,
                  content: 'Toutenkarthon',
                  data: 'Toutenkarthon',
                },
                {
                  id: 2,
                  type: 'GIF',
                  paragraph: 2,
                  content: 'https://giant.gfycat.com/WateryArtisticHamadryad.gif',
                  data: 'https://giant.gfycat.com/WateryArtisticHamadryad.gif',
                },
                {
                  id: 3,
                  type: 'GIF',
                  paragraph: 2,
                  content: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                  data: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                },
              ],
            },
            {
              id: 4,
              title: 'La pyrapide de Khéops',
              text: `La Pyramide Khéops possède quatre faces. C’est donc un carré qui mesure 230 mètres de chaque côté et dont chaque face est un triangle. La hauteur de la pyramide est de 147 mètres, ou plutôt 135 mètres depuis que son sommet c’est effondré et qu’elle a perdu 12 mètres de hauteur. Les détails de sa construction ont toujours été mystérieuse. \n\nLes bâtisseurs égyptiens ont réalisé la pyramide de Khéops en seulement 20 ans. Ils ont utilisé plus de 2,5 millions de blocs de granite. Chaque bloc pèse 2 tonnes soit le poids d’un jeune éléphant. Pour la construction, les 20 000 bâtisseurs étaient munis de toutes sortes d’outils comme des pieux, des poids ou encore des pelles.`,
              image: 'https://giant.gfycat.com/WateryArtisticHamadryad.gif',
              content: [
                {
                  id: 0,
                  type: 'GIF',
                  paragraph: 1,
                  content: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                  data: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                },
                {
                  id: 1,
                  type: 'GIF',
                  paragraph: 1,
                  content: 'https://giant.gfycat.com/WateryArtisticHamadryad.gif',
                  data: 'https://giant.gfycat.com/WateryArtisticHamadryad.gif',
                },
                {
                  id: 2,
                  type: 'word',
                  paragraph: 2,
                  content: 'Pyramide',
                  data: 'Pyramide',
                },
                {
                  id: 3,
                  type: 'GIF',
                  paragraph: 2,
                  content: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                  data: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                },
              ],
            },
            {
              id: 5,
              title: 'Le rôle',
              text: "Durant l'Antiquité, les pyramides d'Égypte ont été construites pour servir de tombeaux. Elles accueillent les corps momifiés des pharaons et de leurs épouses. La forme du monument symbolise un rayon de soleil. Elles devaient permettre aux défunts de rejoindre plus facilement le dieu du soleil, Râ. Enfin, elles garantissent un repos éternel en empêchant des intrus d’entrer.",
              image: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
              content: [
                {
                  id: 0,
                  type: 'word',
                  paragraph: 1,
                  content: 'Râ',
                  data: 'Râ',
                },
                {
                  id: 1,
                  type: 'GIF',
                  paragraph: 1,
                  content: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                  data: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                },
              ],
            },
            {
              id: 6,
              title: "La pyramide aujourd'hui",
              text: 'Bien qu’elle soit toujours debout, la pyramide de Khéops a perdu plusieurs blocs à son sommet mais également son revêtement en calcaire qui lui donnait une couleure plus blanche. La pyramide est le plus vieux monument du monde et a été ajouté au classement des 7 Merveilles du monde antique et est la seule à être encore debout. Elle fait maintenant parti des 7 nouvelles Merveilles du monde au côté du Colisée de Rome ou de la Grande muraille de Chine.',
              image: 'https://giant.gfycat.com/WateryArtisticHamadryad.gif',
              content: [
                {
                  id: 0,
                  type: 'word',
                  paragraph: 1,
                  content: 'Colissée',
                  data: 'Colissée',
                },
                {
                  id: 1,
                  type: 'GIF',
                  paragraph: 1,
                  content: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                  data: 'https://giant.gfycat.com/FilthyFelineBorzoi.gif',
                },
                {
                  id: 2,
                  type: 'word',
                  paragraph: 2,
                  content: 'La Muraille de Chine',
                  data: 'La Muraille de Chine',
                },
                {
                  id: 3,
                  type: 'GIF',
                  paragraph: 2,
                  content: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                  data: 'https://giant.gfycat.com/JoyousAnyFlatcoatretriever.gif',
                },
              ],
            },
          ],
        },
        {
          id: 1,
          locked: true,
          image: 'https://s27.postimg.org/wm6361ygz/rhodes_colosse_image11.jpg',
          name: 'Le colosse de Rhodes',
          period: 'antiquity',
          description: 'Le plus ancien traité de paix encore existant est vieux de 3200 ans entre l’Égypte et l’Empire hittite !',
          duration: 15,
          nbPages: 17,
          availability: '24/12',
        },
        {
          id: 2,
          locked: true,
          image: 'https://s28.postimg.org/fdzty1vfh/mausolee.jpg',
          name: "Le mausolée d'Halicarnasse",
          period: 'antiquity',
          description: "Plonge dans l'histoire du mausolée le plus fastueux du monde Antique !",
          duration: 18,
          nbPages: 32,
          availability: '24/12',
        },
        {
          id: 3,
          locked: true,
          image: 'https://s23.postimg.org/qdsxq3igr/jardins.jpg',
          name: 'Les jardins suspendus',
          period: 'antiquity',
          description: "Découvre l’un des plus beau lieu du monde Antique. Merveille d'architecture, de technologie et de végétation !",
          duration: 10,
          nbPages: 12,
          availability: '24/12',
        },
        {
          id: 4,
          locked: true,
          image: 'https://s24.postimg.org/3yeq7gw1h/artemis.jpg',
          name: "Le temple d'Artemis",
          period: 'antiquity',
          description: "Le temple d'Artémis à Éphèse est dans l'Antiquité l'un des plus importants sanctuaires de la Nature sauvage !",
          duration: 30,
          nbPages: 42,
          availability: '24/12',
        },
        {
          id: 5,
          locked: true,
          image: 'https://s29.postimg.org/iubugy9bb/zeus.jpg',
          name: 'Le statue de Zeus',
          period: 'antiquity',
          description: 'Part à la découverte de la gigantesque statue de Zeus à Olympie, la cité des Dieux !',
          duration: 8,
          nbPages: 9,
          availability: '24/12',
        },
        {
          id: 6,
          locked: true,
          image: 'https://i.ytimg.com/vi/kRTPugHpUho/maxresdefault.jpg',
          name: "Le phare d'Alexandrie",
          period: 'antiquity',
          description: 'Cette tour imposante était l’un des premier phare au monde et une prouesse technologique pour l’époque !',
          duration: 20,
          nbPages: 35,
          availability: '24/12',
        },
      ],
    },
    {
      id: 1,
      image: 'https://s30.postimg.org/sa6i19ze9/mozart.jpg',
      name: 'Les compositeurs classiques',
      period: 'modernTimes',
      description: "Mozart, Beethoven ou encore Chopin : découvre l'art de ces grands compositeurs !",
      nbStories: 4,
      locked: false,
      histories: [
        {
          id: 0,
          locked: true,
          image: 'https://s23.postimg.org/otellv1ez/mozart_wolfgang_amadeus_527a7a17c1157.jpg',
          name: 'Wolfgang Amadeus Mozart',
          period: 'modernTimes',
          description: 'Va à la rencontre de Mozart, l’enfant prodige de la musique classique en découvrant la grandeur de son Oeuvre !',
          duration: 20,
          nbPages: 35,
          availability: '25/12',
        },
        {
          id: 1,
          locked: true,
          image: 'https://s24.postimg.org/6fczcddut/maxresdefault.jpg',
          name: 'Ludwig Van Beethoven',
          period: 'modernTimes',
          description: 'Découvre le destin du dernier grand compositeur du classicisme !',
          duration: 10,
          nbPages: 17,
          availability: '25/12',
        },
        {
          id: 2,
          locked: true,
          image: 'https://s27.postimg.org/s9re3is4j/chopin_frederic_portrait_chopin_classiquenews.jpg',
          name: 'Frédéric Chopin',
          period: 'modernTimes',
          description: "Sa musique est encore aujourd'hui l'une des plus jouées et demeure un passage indispensable au piano !",
          duration: 18,
          nbPages: 32,
          availability: '25/12',
        },
        {
          id: 3,
          locked: true,
          image: 'https://s27.postimg.org/4equiz8ir/x600x337_fotorcreated_24_jpg_pagespeed_ic_94_YKYG.jpg',
          name: 'Antonio Vivaldi',
          period: 'modernTimes',
          description: 'Il a été l’un des virtuoses du violon les plus célèbres de la période baroque !',
          duration: 5,
          nbPages: 12,
          availability: '25/12',
        },
      ],
    },
    {
      id: 2,
      image: 'https://i.ytimg.com/vi/QrOQiknOE9w/maxresdefault.jpg',
      name: 'Les grottes préhistoriques',
      period: 'preHistory',
      description: "Explore les grottes de la Préhistoire et admire les plus vieux chefs d'oeuvre de l’histoire de l’Humanité !",
      nbStories: 5,
      locked: true,
      price: 5.99,
      availability: '25/12',
    },
    {
      id: 3,
      image: 'https://s29.postimg.org/r0lsah5xj/lumieres.jpg',
      name: 'Les philosophes des Lumières',
      period: 'modernTimes',
      description: 'Part à la rencontre de ceux qui ont changé notre façon de voir le monde. Les philosophes des Lumières !',
      nbStories: 4,
      locked: true,
      price: 5.99,
      availability: '25/12',
    },
    {
      id: 4,
      image: 'https://s29.postimg.org/s8jfk0mp3/porcelaine.jpg',
      name: "L'art de la porcelaine chinoise",
      period: 'middleAge',
      description: "Voyage à la découverte de l'art de la porcelaine chinoise à travers les âges, de la céramique Xing aux vases Ming !",
      nbStories: 3,
      locked: true,
      price: 5.99,
      availability: '25/12',
    },
    {
      id: 5,
      image: 'https://s24.postimg.org/gx6anhjth/picasso.jpg',
      name: 'La peinture par Pablo Picasso',
      period: 'contemporaryTimes',
      description: 'Découvre les plus belles oeuvres du peintre Pablo Picasso pour le comprendre de sa période bleu au cubisme !',
      nbStories: 5,
      locked: true,
      price: 5.99,
      availability: '25/12',
    },
    {
      id: 6,
      image: 'https://s27.postimg.org/xvmb61xmb/maya.jpg',
      name: 'La civilisation Maya',
      period: 'antiquity',
      description: 'Admire les créations de l’une des plus grandes civilisations d’Amérique du Sud à travers leurs temples & sculptures !',
      nbStories: 7,
      locked: true,
      price: 5.99,
      availability: '25/12',
    },
  ],
  facts: [
    {
      id: 0,
      period: 'preHistory',
      content: "C'est en pourchassant un lapi qu'un chien qui accompagnait un groupe d'adolescent a découvert la grotte de Lascaux en 1940.",
    },
    {
      id: 1,
      period: 'antiquity',
      content: 'Le plus ancien traité de paix encore existant est vieux de 3200 ans entre l’Égypte et l’Empire hittite !',
    },
    {
      id: 2,
      period: 'middleAge',
      content: 'Le premier roman de l’histoire a été écrit en l’an 1007 au Japon par une noble japonaise du nom de Murasaki Shikibu !',
    },
    {
      id: 3,
      period: 'mondernTimes',
      content: 'Le catalogue Köchel est un répertoire qui recense les travaux de Mozart : il compte actuellement 893 oeuvres !',
    },
    {
      id: 4,
      period: 'contemporaryTimes',
      content: 'Après l’Exposition universelle de Paris en 1889, tout comme les autres constructions : la Tour Eiffel était censée être démontée !',
    },
  ],
}
