/* @flow */

export default {
  fetchRepositories: () => new Promise(() => null),
}

export const API = {
  themes: [
    {
      id: 0,
      image: 'https://s24.postimg.org/3yeq7gw1h/artemis.jpg',
      name: 'Les 7 merveilles du monde',
      period: 'antiquity',
      description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
      nbStories: 7,
      locked: false,
      histories: [
        {
          id: 0,
          locked: false,
          image: 'https://s27.postimg.org/bskr443v7/slide1_1_1024x475.jpg',
          name: 'La pyramide de Kheops',
          period: 'antiquity',
          description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
          duration: 20,
          nbPages: 35,
        },
        {
          id: 1,
          locked: true,
          image: 'https://s27.postimg.org/wm6361ygz/rhodes_colosse_image11.jpg',
          name: 'Le colosse de Rhodes',
          period: 'antiquity',
          description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
          duration: 10,
          nbPages: 17,
        },
        {
          id: 2,
          locked: true,
          image: 'https://s28.postimg.org/fdzty1vfh/mausolee.jpg',
          name: "Le mausolée d'Halicarnasse",
          period: 'antiquity',
          description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
          duration: 18,
          nbPages: 32,
        },
        {
          id: 3,
          locked: true,
          image: 'https://s23.postimg.org/qdsxq3igr/jardins.jpg',
          name: 'Les jardins suspendus',
          period: 'antiquity',
          description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
          duration: 5,
          nbPages: 12,
        },
        {
          id: 4,
          locked: true,
          image: 'https://s24.postimg.org/3yeq7gw1h/artemis.jpg',
          name: "Le temple d'Artemis",
          period: 'antiquity',
          description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
          duration: 30,
          nbPages: 42,
        },
        {
          id: 5,
          locked: true,
          image: 'https://s29.postimg.org/iubugy9bb/zeus.jpg',
          name: 'Le statue de Zeus',
          period: 'antiquity',
          description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
          duration: 3,
          nbPages: 9,
        },
        {
          id: 6,
          locked: true,
          image: 'https://i.ytimg.com/vi/kRTPugHpUho/maxresdefault.jpg',
          name: "Le phare d'Alexandrie",
          period: 'antiquity',
          description: 'Découvre les plus belles constructions du monde Antique, des plaines égyptiennes aux montagnes grecques !',
          duration: 20,
          nbPages: 35,
        },
      ],
    },
    {
      id: 1,
      image: 'https://i.ytimg.com/vi/QrOQiknOE9w/maxresdefault.jpg',
      name: 'Les grottes préhistoriques',
      period: 'preHistory',
      description: "Explore les grottes de la Préhistoire et admire les plus vieux chefs d'oeuvre de l’histoire de l’Humanité !",
      nbStories: 5,
      locked: true,
    },
    {
      id: 2,
      image: 'https://s30.postimg.org/sa6i19ze9/mozart.jpg',
      name: 'Les compositeurs classiques',
      period: 'modernTimes',
      description: "Mozart, Beethoven ou encore Chopin : découvre l'art de ces grands compositeurs !",
      nbStories: 12,
      locked: true,
    },
    {
      id: 3,
      image: 'https://s29.postimg.org/r0lsah5xj/lumieres.jpg',
      name: 'Les philosophes des Lumières',
      period: 'modernTimes',
      description: 'Part à la rencontre de ceux qui ont changé notre façon de voir le monde. Les philosophes des Lumières !',
      nbStories: 4,
      locked: true,
    },
    {
      id: 4,
      image: 'https://s29.postimg.org/s8jfk0mp3/porcelaine.jpg',
      name: "L'art de la porcelaine chinoise",
      period: 'middleAge',
      description: "Voyage à la découverte de l'art de la porcelaine chinoise à travers les âges, de la céramique Xing aux vases Ming !",
      nbStories: 3,
      locked: true,
    },
    {
      id: 5,
      image: 'https://s24.postimg.org/gx6anhjth/picasso.jpg',
      name: 'La peinture par Pablo Picasso',
      period: 'contemporaryTimes',
      description: 'Découvre les plus belles oeuvres du peintre Pablo Picasso pour le comprendre de sa période bleu au cubisme !',
      nbStories: 5,
      locked: true,
    },
    {
      id: 6,
      image: 'https://s27.postimg.org/xvmb61xmb/maya.jpg',
      name: 'La civilisation Maya',
      period: 'antiquity',
      description: 'Admire les créations de l’une des plus grandes civilisations d’Amérique du Sud à travers leurs temples & sculptures !',
      nbStories: 7,
      locked: true,
    },
  ],
}
